<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Pizzzza</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Teste TLO">
    <meta name="Author Site" content="Julia Brazolim">

    <!-- Favicon -->
    <link rel="icon" style="width:40px; height:50px;" href="brand/brand1.png"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Login CSS -->
    <link rel="stylesheet" href="css/style.css">
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
     <div class="container">
        <a class="navbar-brand" href="#">
          <img class="d-inline-block align-top" src="brand/brand1.png" width="30" height="30" alt="Um livro aberto, logotipo">
          Pizzzza
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      </div>
    </nav>
    <!-- /. Navigation -->

    <!-- Description -->
      <div class="container h-100 d-inline-block">
        <div class="py-5 text-center">
          <img class="d-block mx-auto mb-4" src="brand/brand.png" width="10%">
          <h2>Pizzzza</h2>
          <p class="text-muted">Bem-vindo(a)!</p>
          <p class="text-light">Digite PIZZA ou PIZZARIA para encontrar as melhores pizzarias!</p><br>
        </div>

        <!-- Search -->
        <nav class="navbar d-flex justify-container-center">
          <form action="food.php" method="GET" class="form-inline">
            <input class="form-control mr-sm-2" type="text" name="zomquery" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-outline-success my-2 my-sm-0" name="zomsubmit">Pesquisar</button>
          </form>
        </nav>

        <?php
          if (isset($_GET['zomsubmit'])) {
            $zomquery = $_GET['zomquery'];
            # Continue running code
          }
          else {
            //echo "Search key not found";
            exit();
          }
          // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
          $ch = curl_init();
          curl_setopt($ch, CURLOPT_URL, "https://developers.zomato.com/api/v2.1/search?q=".$zomquery."&start=0&count=5");
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
          curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
          $headers = array(
            "Accept: application/json",
            "User-Key: 40d6be896ffb3965148c7df5f88f7cae"
            );
          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
          $result = curl_exec($ch);
          if (curl_errno($ch)) {
              echo 'Error:' . curl_error($ch);
          }
          curl_close ($ch);
          $zomdata = json_decode($result);
          $zomrestaurants = $zomdata->restaurants;
          //echo "<pre>"; print_r($zomrestaurants); echo "</pre>";
              if (count($zomrestaurants) == 0) {
                echo "<b>Sem resultados para sua pesquisa</b>";
                exit();
              }
           echo "Encontrado: ".$zomdata->results_found." resultados<br/>";
           echo "Result shown: ".$zomdata->results_start." to ".$zomdata->results_shown."<br/><br/>";
          foreach ($zomrestaurants as $restaurant) {
            echo "<h3>".@$restaurant->restaurant->name."</h3>";
              if ($restaurant->restaurant->thumb != "") {
                echo "<img width='330' src='".@$restaurant->restaurant->thumb."' /><br/>";
              }

            echo "Restaurante ID: ".@$restaurant->restaurant->id."<br/>";
            echo "Nota: ".@$restaurant->restaurant->user_rating->rating_text."( ".@$restaurant->restaurant->user_rating->aggregate_rating."/5 ) Depending upon ".@$restaurant->restaurant->user_rating->votes." votes<br/>";
            echo @$restaurant->restaurant->location->address.", ".@$restaurant->restaurant->location->city." <a href='".@$restaurant->restaurant->url."'>Visitar página do restaurante</a><br/>";
            echo "<br/><hr>";
            //echo "<pre>"; print_r($restaurant->restaurant); echo "</pre>";
          }
        ?>
        <!-- /. Search -->
      </div>
    <!-- /. Description -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Pooper.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>
